### ISSUE TITLE
(Sort of) compatibility issues with Janitors Closet

### ISSUE THREAD

**Issue by Lafreakshow** [radistmorse/KSPAdjustableModPanel#2]
**Short version:** As far as I can tell the mods don't cause any serious or persistent issues but when changing anything in AMP, all buttons hidden by Janitors Closet will reappear in the app launcher. They will return to normal again on the next switch to that scene. (Currently playing on 1.9.1 with the appropriate latest version of the mods)

Bascially it goes (for example):

Starting Scene: In Flight -> Move any button to folder via JC -> hide or unhide any button via AMP -> moved buttons visible again -> go to KSC -> go to In flight -> moved button corectily hidden again

**Detailed Version:** The primary purpose of Janitors Closet is to hide certain parts, but it also provides featuresvery similar to this mod, albeit in a less apealing UI, it's finicky and unintuitive, which is why I prefer to use Adjustable Mod Panel over it for this. However, it allows you to move AppLauncher buttons into folders represented by new buttons, allowing one to declutter the applauncher without completely hiding a buttom by compressing multiple apps into one button.

Now added to a folder, the button will (pr should, JC seems to have some issues with this on it own already) be hidden from the regular AppLauncher, but whenever something is changed in AdjustableModPannel (I.e. Hide or display a button or pin one of the folders (this is really why I would like to use both mods)), all buttons moved to folders will appear in the AppLauncher again. They will also still appear in the folder so essentially, they exist twice. As mentioned before, as far as I can tell, this doesn't cause serious or persistent issues. Everything seems to return to the expected state when the scene is loaded the next time. 

I'm not sure about the no serious issues part though and that's why I have two Questions/Requests here.

1) The obvious one, do any serious problems come to mind? I don't expect you to go and do a detailed analysis here, I will bump into them eventually. But if you happen to have an idea here, I'd be very interested in it.

2) Is it possible to add some kind of compatibility mode or check to make the mods play more nicely together? Essentially all AMP would have to do is keep track of buttons hidden by Janitors Closet and/or contained in folders and then leave them alone. The major thing here is that I can't have buttons hidden via AMP and still have them appear in a folder. They must be enabled in AMP and then Janitors closet can move them to the folder (or hide them).

I expect this is far from as simple as this sounds. I am a programmer but neither do I know C# nor do I have any idea how KSP modding works so my glances over the code for both mods didn't net me much here but perhaps you have an idea.

I'm am aware that this would possibly require changes to both mods or maybe it is only possible with changes to Janitors Closet, the reason I came here with this is mostly that I have the impression that Linuxgurugamer is much more busy than you are, considering the number of mods he maintains. But if you can't or don't want to take on this issue I'm just as happy to take it there. It'd be understandable considering the two mods essentially replace each other and the inconvenience that brought me here can be fixed in multiple way by either mod.

One other possible solution that avoids compatibility code altogether could be to implement a folder feature into AMP itself. Though I have no idea how dificult and time consuming any of this is.

In the end I'm not expecting much out of this, so no pressure. I'm mostly just throwing around some thoughts here. I would be happy to help with any further questions or testing related to this.  should you need any extra information, let me know and don't be afraid to shove me off if you aren't interested at all, I'll happily go bother Linuxgurugamer in that case.

**Comment by radistmorse** [comment]
First of all, I can explain you the behavior that you see. The mod doesn't update the panel constantly to save CPU. I only update the state of the panel once, during the scene transition, and then every time the user changes the configuration. I guess JC does the same, but maybe AMP does this first simply by being first alphabetically. When you change visibility of the button, AMP updates the state of all the buttons. There is a field in the mod buttons called "VisibleInScenes", which lists all the scenes in which the button is supposed to appear. This is a stock behavior, so the mod doesn't even introduce anything specific, it just changes that field in accordance with the user configuration. What it then additionally does - it updates the visibility state of the button based on that field. So if the button was supposed to be visible in a scene - it will be. I guess that's why all the buttons hidden by JC reappear.

I don't think it's possible to fix this in AMP. The mod panel is very buggy. I can never know why the button that's supposed to be seen is actually not. And if I switch off the behavior where AMP updates the button states, it will bring a lot of errors. As for JC, it could change "VisibleInScenes" to represent the actual visibility of the button. The downside to this would be, that as soon as AMP sees VisibilityInScenes being changed from outside, it black-lists and ignores the mod, so you want be able to configure that mod with AMP anymore.

Intermod interaction is always a pain, since neither of the developers is usually interested in backward compatibility. I don't expect any problems to come out of this, since AMP only changes things when it is absolutely sure that everything is OK. As soon as it encounters any weird behavior, it instantly black-lists the button and stops working with it. And as far as I understand - the only time when you face the problem is during the configuration. So my advise would be: configure everything once, and then forget about AMP altogether. That was the idea behind it anyway, even if the GUI is nice to look at :)

**Comment by Lafreakshow** [comment]
Awesome and quick reply. Thanks for that!

About what I expected. It's good to know that it's nothing serious. In that case I can indeed just set it up and then avoid touching it. It was never a gramebreaking thing, just mildly annoying. Who knows, if this annoys me enough or I get another kick of motivation I might go and learn C# and hack something together. I hear the jump from Java isn't that hard. Maybe just a hacky manual blacklist or something. or I build my own folder solution with AMP in mind. I'm known to go to ridicolous lengths to fix minor inconveniences that aren't even present in 99% of gameplay. That's how I got into Skyrim Modding and that's how I got into Factorio modding. Anyway, that's none of your concern and I'm just rambling.

In any case, I am insanely thankful that this mod exists. With the number of mods I run the AppLauncher in the VAB is so full of buttons whose only purpose is to bring up a useless info or some config window that it's almost stretching above the symetry controls and you can imagine how bad it is in flight. The large content rich overhaul mods always get all the attention but it's the smaller QoL things that have the greates impact, at least if you ask me. I guess I could say the same about Janitors Closet but I discovered your mod first so you get the credit. 

Have a wonderful day!
